const TryAiDataSet = {
  categories: ["Fast Food", "Italian", "Snack", "Asian", "Healthy"],
  meals: [
    {
      id: 1,
      name: "Burger",
      price: 80,
      benefit: "High protein, tasty fast food",
      ingredients: "Bun, beef patty, lettuce, tomato, cheese",
      calories: 350,
      category: "Fast Food",
      newest: false,
      origin: "USA",
      spicyLevel: "Medium",
      isVegetarian: false,
      preparationTime: 15,
    },
    {
      id: 2,
      name: "Pizza",
      price: 150,
      benefit: "Rich in carbs, family food",
      ingredients: "Dough, cheese, tomato sauce, toppings",
      calories: 700,
      category: "Italian",
      newest: true,
      origin: "Italy",
      spicyLevel: "Low",
      isVegetarian: true,
      preparationTime: 30,
    },
    {
      id: 3,
      name: "Pasta",
      price: 100,
      benefit: "Good energy source, Italian cuisine",
      ingredients: "Pasta, sauce, veggies, chicken",
      calories: 450,
      category: "Italian",
      newest: true,
      origin: "Italy",
      spicyLevel: "Low",
      isVegetarian: false,
      preparationTime: 25,
    },
    {
      id: 4,
      name: "Chicken Roll",
      price: 60,
      benefit: "Quick snack, protein rich",
      ingredients: "Paratha, chicken, onion, spices",
      calories: 250,
      category: "Snack",
      newest: false,
      origin: "India",
      spicyLevel: "High",
      isVegetarian: false,
      preparationTime: 10,
    },
    {
      id: 5,
      name: "Fried Rice",
      price: 90,
      benefit: "Full meal, balanced nutrients",
      ingredients: "Rice, egg, vegetables, chicken",
      calories: 550,
      category: "Asian",
      newest: false,
      origin: "China",
      spicyLevel: "Medium",
      isVegetarian: false,
      preparationTime: 20,
    },
    {
      id: 6,
      name: "Sandwich",
      price: 50,
      benefit: "Light meal, easy to digest",
      ingredients: "Bread, veggies, cheese, mayo",
      calories: 200,
      category: "Snack",
      newest: true,
      origin: "UK",
      spicyLevel: "Low",
      isVegetarian: true,
      preparationTime: 5,
    },
    {
      id: 7,
      name: "Biryani",
      price: 180,
      benefit: "Rich in flavor, filling meal",
      ingredients: "Rice, mutton/chicken, spices",
      calories: 900,
      category: "Asian",
      newest: true,
      origin: "India",
      spicyLevel: "High",
      isVegetarian: false,
      preparationTime: 45,
    },
    {
      id: 8,
      name: "Salad",
      price: 70,
      benefit: "Healthy, low calories",
      ingredients: "Lettuce, cucumber, tomato, olive oil",
      calories: 120,
      category: "Healthy",
      newest: true,
      origin: "Greece",
      spicyLevel: "None",
      isVegetarian: true,
      preparationTime: 10,
    },
  ],
};

export default TryAiDataSet;
